### ISSUE TITLE
Content getting falsely flagged as previews

### ISSUE THREAD

**Issue by warderj4** [Avnsx/Fansly-Downloader-App#91]
Version 0.4 is not downloading videos from 2 most recent posts for a specific model. It does appear to download all other media from this model. I have had no issue downloading from a few other models.

Videos from this model require an active subscription for access - I can provide an account with access for troubleshooting.

For testing I tried 0.3.5 which does download the videos, but at 720p becuse of that previous issue that was resolved in 0.4

**Comment by Avnsx** [comment]
Thanks for reporting this!

E-Mail me an account that has access to these posts at ``AvnDev[at]protonmail[dot]com`` and I'll fix it asap

**Comment by Avnsx** [comment]
The problem lies not with the Fansly downloader itself, but rather with the authorization token you've in the config.ini file, which likely belongs to an account that lacks access to the provided media. The account you specifically created for this purpose, however, functioned properly.

**Comment by warderj4** [comment]
Thanks for looking into this. I did test with the account I provided and the same token worked for 0.3.5. There must be something else wrong at my end that I'll keep looking into. Thanks again.

**Comment by Avnsx** [comment]
The flagging as review was a little bit interesting to me too, might look into that again.

Apart from that ``update_recent_download`` is a very efficient re-write of the old functionality, which is why it should now just always stay on ``Auto``. You can now actually easily update previous downloads with it, without any hassle, very quickly.

**Comment by chriskev01** [comment]
This might be a coincidence, but for me, the videos that downloaded as previews were the same ones that had the "Auto 4k" option from the gear icon, and would only download as 720p with the previous version instead of 2160p.  Now they download at 2160p, but are all flagged as previews.

**Comment by Avnsx** [comment]
Should be fixed with commit https://github.com/Avnsx/Fansly-Downloader-App/commit/2736a5417d0a6db75f56064371b305fdaafcd52b

**Comment by warderj4** [comment]
Just tested with latest commit, everything's working perfectly for me. Thanks for your work.
